name: tumbleweed-dnf-toolbox
on:
  push:
    branches:
      - master
    paths:
      - 'images/opensuse/tw/dnf/**'
      - '.github/workflows/tumbleweed-dnf.yaml'


jobs:
  build:
    name: Build and push tumbleweed-dnf-toolbox image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Get date snapshot
      run: echo "SNAPSHOT=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Get Git short Hash
      run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
    
    - name: Setup Multi-Arch builds
      run: sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2.2.1
      with:
        image: tumbleweed-dnf-toolbox
        tags: ${{ env.SHORT_SHA }} ${{ env.SNAPSHOT }} latest
        archs: arm64, amd64
        oci: true
        context: images/opensuse/tw/dnf
        dockerfiles:
          ./images/opensuse/tw/dnf/Dockerfile
    
    - name: Push to GHCR
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@v2.1.1
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags:  ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/${{ github.actor }}
        username: ${{ github.actor }}
        password: ${{ secrets.CR_TOKEN }}

    - name: Use the image
      run: echo "New image has been pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"